[package]
name = "seum"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "*"
glam = { version = "*", features = ["core-simd", "fast-math"] }
bevy = {version = "*", features = ["webgpu", "multi_threaded", "common_api", "mesh_picking", "bevy_picking", "3d_bevy_render", "bevy_text", "ui", "bevy_asset", "morph", "std", "hotpatching"]}
bevy_slugtext = "0.1.0"
compactly = "0.1.6"
redb = { version = "^4" }
# rayon = { version = "*"}

[profile.dev]
opt-level = 1

[profile.dev.package."*"]
opt-level = 3
incremental = false

[profile.release]
opt-level = 3
lto = "thin"
codegen-units = 1

# Optimize for size in the wasm-release profile to reduce load times and bandwidth usage on web.
[profile.wasm-release]
# Default to release profile values.
inherits = "release"
# Optimize with size in mind (also try "z", sometimes it is better).
# Slightly slows compile times, great improvements to file size and runtime performance.
opt-level = "s"
# Strip all debugging information from the binary to slightly reduce file size.
strip = "debuginfo"
